---
title: "homework_four"
author: "Isaac Buabeng"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question One

#### A.
```{r}
z <- 1.1 ^ 2.2 ^ 3.3

print(z)
```


#### B.
```{r}
z <- (1.1 ^ 2.2) ^ 3.3

print(z)
```

#### C.
```{r}
z <- 3 * 1.1 ^ 3 + 2 * 1.1 ^ 2 + 1

print(z)
```

# Question Two
#### A.
```{r}
x <- c(seq(1, 7), 8, seq(7,1))

print(x)
```

#### B.
```{r}
y <- seq(1:5)

print(y)

rep(x=y, times=y)
```

#### C.
```{r}
c <- rep(5:1)

print(c)

rep(x=c, times=1:5)
```


# Question Three
```{r}
#let's set seed so our values don't keep changing
set.seed(10)

#define x and y
x <- runif(1)
print(x)

y <- runif(1)
print(y)

# let's find r
r <- sqrt(x ^ 2 + y ^ 2)

print(r)

# let's find theta
theta <- -asin(y/r)

print(theta)
```

# Question four
#### A.
```{r}
#make queue
queue <- c("sheep", "fox", "owl", "ant")

print(queue)

#add the serpent
queue <- c(queue, "serpent")
print(queue)
```


#### B.
```{r}
queue <- queue[-1]
print(queue)
```

####  C.
```{r}
queue <- c("donkey", queue)

print(queue)
```

#### D.
```{r}
queue <- queue[-5]

print(queue)
```

#### E.
```{r}
queue <- queue[-3]

print(queue)
```

#### F.
```{r}
queue <- c(queue[1], queue[2], "aphid", queue[3])

print(queue)
```

#### G.
```{r}
which(queue == "aphid")
```

# Question 5
```{r}
vec <- seq(1:100)
which(!(vec %% 2 == 0 | vec %% 3 == 0 | vec %% 7 == 0))
```

