---
title: "homework_five"
author: "Isaac Buabeng"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Question One
```{r matrices and dataframes 1}
# I would like to set seed first to avoid changing results or conflicts
set.seed(123)

# assigning a single random inter between 3 and 10 to n_dims
n_dims <- sample(3:10, size = 1)

print(n_dims)

#create a vector of consecutive integers from 1:n_dims^2
vec <- c(1:n_dims ^ 2)
print(vec)

# randomly sample to reshuffle the values in the new vector
shuffled_vec <- sample(vec)

# creating a square matrix with the shuffled elements
shuf_matrix <- matrix(shuffled_vec, nrow = n_dims, ncol=n_dims)
print(shuf_matrix)

# transposinng the matrix
trns_matrix <- t(shuf_matrix)

print(trns_matrix)

nrow(trns_matrix)

# calculating the sum and means of elements in the first and last rows
sum(trns_matrix[1,] )
sum(trns_matrix[9,])

mean(trns_matrix[1,])
mean(trns_matrix[9,])

# using the eigen function on my matrix
eigen_output <- eigen(trns_matrix)

print(eigen_output) #looks like we generated a bunch of characteristic roots

# digging in to find out  the actual types of numbers generated
typeof(eigen_output$values)
typeof(eigen_output$vectors) #They are all complex numbers of latent roots
```

# Question 2
```{r matrices and dataframes 2}
# a 4 x 4 matrix filled with random uniform values
my_matrix <- matrix(data=runif(16), nrow=4, ncol=4)
print(my_matrix)

# a 100-element vector of TRUE or FALSE values
my_logical <- sample(c(TRUE, FALSE), size = 100, replace = TRUE)
print(my_logical)

# a 26-element vector of all the lower-case letters in random order
my_letters <- sample(letters, size = 26, replace = FALSE)
print(my_letters)

# a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector
my_list <- list(c(my_matrix[2,2], my_logical[2], my_letters[2]))
print(my_list)

typeof(my_matrix[2,2])
typeof(my_logical[2])
typeof(my_letters[2])
typeof(my_list) # its a list
```


# Question 3
```{r matrices and dataframes 3}
# creating a dataframe with two variables
my_unis <- runif(26, min = 0, max =10)
my_letters <- sample(LETTERS, size = 26, replace = FALSE)

my_df <- data.frame(my_unis, my_letters)

print(my_df)

#selecting four random rows and replacing them with NAs in my df
my_df$my_unis <- replace(my_df$my_unis, list=sample(my_df$my_unis, size = 4), values=NA)

print(my_df)

# identifying the portions of the first variable with missing spots
which(is.na(my_df$my_unis))

# rearrage the second column in alphabetical order
my_df[order(my_df$my_letters),]

#calculating the mean of the first variable
d <- mean(my_df$my_unis, na.rm = TRUE)
print(d)
```

